---
name: Stale Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'Issues become stale 90 days after last activity and are closed 14 days after that.  If this issue is still relevant bump it or assign it.'
          stale-pr-message: 'Pull Requests become stale 90 days after last activity and are closed 14 days after that.  If this pull request is still relevant bump it or assign it.'
          days-before-stale: 90
          days-before-close: 14
          exempt-all-assignees: true
          ascending: true
          operations-per-run: 250
          exempt-issue-labels: request
